apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: coffee-service
  name: coffee-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 9080-9080
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: coffee-service
  type: ClusterIP
status:
  loadBalancer: {}
