apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: inventory-failover
  name: inventory-failover
spec:
  ports:
  - name: 8083-8083
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: 9083-9083
    port: 9083
    protocol: TCP
    targetPort: 9083
  selector:
    app: inventory-failover
  type: ClusterIP
status:
  loadBalancer: {}
