apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: inventory-service
  name: inventory-service
spec:
  ports:
  - name: 8082-8082
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: 9082-9082
    port: 9082
    protocol: TCP
    targetPort: 9082
  selector:
    app: inventory-service
  type: ClusterIP
status:
  loadBalancer: {}
