apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: order-service
    spec:
      containers:
      - image: hexhoc/kbe-coffeehouse-order-service
        name: kbe-coffeehouse-order-service
        resources: {}
        env: 
          - name: JAVA_TOOL_OPTIONS
            value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9081
          - name: SPRING_PROFILES_ACTIVE
            value: docker

status: {}
