version: '3.8'

services:
    db:
        image: postgres
        container_name: postgres-prod
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        container_name: elasticsearch
        ports:
            - 9200:9200
        environment:
            discovery.type: single-node
    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.1
        container_name: kibana
        ports:
            - 5601:5601
        restart: on-failure
        depends_on:
            - elasticsearch
    filebeat:
        build:
            context: ./filebeat
            dockerfile: Dockerfile
        container_name: filebeat
        volumes:
#            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
            - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
        user: root                                                             # Allow access to log files and docker.sock
        restart: on-failure
    jms:
        image: vromero/activemq-artemis
        container_name: jms
        ports:
            - 8161:8161
            - 61616:61616
    coffee-service:
        image: example/kbe-coffeehouse-coffee-service
        container_name: coffee-service
        ports:
            - 8080:8080
            - 9080:9080
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9080
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-prod:5432/postgres
            - SPRING_ARTEMIS_HOST=jms
            - CUSTOM_COFFEEHOUSE_COFFEE-INVENTORY-SERVICE-HOST=http://inventory-service:8082
        depends_on:
            - inventory
            - jms
        restart: on-failure
        #        environment:
        #            SPRING_DATASOURCE_USER: root
        #            SPRING_DATASOURCE_PASSWORD: dbpassword
        #            SPRING_JPA_HIBERNATE_DDL-AUTO: update
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    inventory-service:
        image: example/kbe-coffeehouse-inventory-service
        container_name: inventory-service
        ports:
            - 8082:8082
            - 9082:9082
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9082
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-prod:5432/postgres
            - SPRING_ARTEMIS_HOST=jms
        depends_on:
            - jms
#        environment:
#            SPRING_DATASOURCE_USER: root
#            SPRING_DATASOURCE_PASSWORD: dbpassword
#            SPRING_JPA_HIBERNATE_DDL-AUTO: update
        restart: on-failure
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    inventory-failover:
        image: example/kbe-coffeehouse-inventory-failover
        container_name: inventory-failover
        ports:
            - 8083:8083
            - 9083:9083
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9083
    order-service:
        image: example/kbe-coffeehouse-order-service
        container_name: order-service
        ports:
            - 8081:8081
            - 9081:9081
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9081
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-prod:5432/postgres
            - SPRING_ARTEMIS_HOST=jms
            - CUSTOM_COFFEEHOUSE_COFFEE-SERVICE-HOST=http://coffee-service:8080
        depends_on:
            - coffee-service
            - jms
        restart: on-failure
#        environment:
#            SPRING_DATASOURCE_USER: root
#            SPRING_DATASOURCE_PASSWORD: dbpassword
#            SPRING_JPA_HIBERNATE_DDL-AUTO: update
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"
    gateway:
        image: example/kbe-coffeehouse-gateway
        container_name: gateway
        ports:
            - 9090:9090
            - 9092:9092
        environment:
            - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9092
        depends_on:
            - inventory
            - coffee-service
            - order-service
            - inventory-failover
        restart: on-failure
        labels:
            collect_logs_with_filebeat: "true"
            decode_log_event_to_json_object: "true"

