package com.example.orderservice.entity;

public enum CoffeeOrderEventEnum {
    CANCEL_ORDER, VALIDATE_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATION_FAILED, ALLOCATION_NO_INVENTORY,
    COFFEE_ORDER_PICKED_UP
}
